THNN/Areas/Admin/Controllers/ChuongTrinhKhuyenMaiController.cs
using Microsoft.ReportingServices.RdlExpressions.ExpressionHostObjectModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using THNN.Models;

namespace THNN.Areas.Admin.Controllers
{
    public class ChuongTrinhKhuyenMaiController : Controller
    {
        // GET: Admin/ChuongTrinhKhuyenMai
        public ActionResult Index()
        {
            THNNEntities1 db = new THNNEntities1();
            List<ChuongTrinhGG> danhSachGG = db.ChuongTrinhGGs.ToList();
            return View(danhSachGG);
        }

        public ActionResult ThemMoiSuKien()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemMoiSuKien(ChuongTrinhGG model, HttpPostedFileBase fileAnh)
        {
            THNNEntities1 db = new THNNEntities1();
            List<ChuongTrinhGG> danhSachCTGG = db.ChuongTrinhGGs.ToList();
            ChuongTrinhGG ctggLast = danhSachCTGG.Last();
            String maCT = "";
            String splitMaCT = "";
            long newMaCTInt = 0;
            String newMaCTString = "";
            maCT = ctggLast.MaCT;
            splitMaCT = maCT.Substring(2);
            if (Int64.TryParse(splitMaCT, out newMaCTInt))
            {
                newMaCTInt++; // Thực hiện tăng giá trị
            }
            if (newMaCTInt < 10)
            {
                newMaCTString = "CT00" + Convert.ToString(newMaCTInt);
            }
            else if (newMaCTInt > 10)
            {
                newMaCTString = "CT0" + Convert.ToString(newMaCTInt);
            }

            if(model.PhanTram == 0 || model.PhanTram < 0)
            {
                ModelState.AddModelError("", "Vui lòng nhập phần trăm giảm giá");
                return View(model);
            }

            if (fileAnh != null)
            {
                if (fileAnh.ContentLength > 0)
                {
                    string rootFolder = Server.MapPath("/assets/img/sales-slider/");
                    string pathEmail = rootFolder + fileAnh.FileName;
                    fileAnh.SaveAs(pathEmail);
                    //Luu thuoc tinh url hinhanh
                    model.Poster = "/assets/img/sales-slider/" + fileAnh.FileName;
                }
            }
            else
            {
                model.Poster = null;
            }

            DateTime? date = model.ThoiGianBD;
            string thoiGianBD = date?.ToString("yyyy-MM-dd");
            model.ThoiGianBD = DateTime.Parse(thoiGianBD);

            DateTime? date2 = model.ThoiGianKT;
            string thoiGianKT = date?.ToString("yyyy-MM-dd");
            model.ThoiGianKT = DateTime.Parse(thoiGianKT);


            model.PhanTram = model.PhanTram / 100;
            model.MaCT = newMaCTString;
            db.ChuongTrinhGGs.Add(model);
            db.SaveChanges();


            return RedirectToAction("Index");
        }

        public ActionResult CapNhatCTGG(string id)
        {
            THNNEntities1 db = new THNNEntities1();
            //Tìm đối tượng
            ChuongTrinhGG model = db.ChuongTrinhGGs.Find(id);
            Session["Admin_Update-CTGG"] = model;
            return View(model);
        }

        public ActionResult ThemSanPham(string id)
        {
            THNNEntities1 db = new THNNEntities1();
            //Tìm đối tượng
            var query = db.Database.SqlQuery<SanPham>(
               "select sp.* " +
               "from ChuongTrinhGG ctgg right join SanPham sp on ctgg.MaCT = sp.MaCT " +
               "where sp.MaCT = '"+id+"' " +
               "union " +
               "select * from SanPham " +
               "where MaCT IS NULL");
            List<SanPham> list = query.ToList();
            Session["MACT_Update-CTGG"] = id;
            return View(list);
        }

        [HttpPost]
        public ActionResult ThemSanPham(bool itemChecked, string maSP, string maCT)
        {
            THNNEntities1 db = new THNNEntities1();
            //Tìm đối tượng
            SanPham sp = db.SanPhams.Find(maSP);
            if (itemChecked)
            {
                
                sp.MaCT = maCT;
            }
            else
            {
                sp.MaCT = null;
            }
            
            db.SaveChanges();
            return View();
        }

        [HttpPost]
        public ActionResult ThemSanPhamAll(bool ItemChecked, string[] ListSP, string MaCT)
        {
            THNNEntities1 db = new THNNEntities1();
            //Tìm đối tượng
            if(ListSP != null)
            {
                for(var i = 0; i< ListSP.Length; i++)
                {
                    SanPham sp = db.SanPhams.Find(ListSP[i]);
                    if (ItemChecked)
                    {

                        sp.MaCT = MaCT;
                    }
                    else
                    {
                        sp.MaCT = null;
                    }
                }
            }
            

            db.SaveChanges();
            return View();
        }






        [HttpPost]
        public ActionResult CapNhatCTGG(ChuongTrinhGG model, HttpPostedFileBase fileAnh)
        {
            THNNEntities1 db = new THNNEntities1();
            ChuongTrinhGG modelCTGG = Session["Admin_Update-CTGG"] as ChuongTrinhGG;
            //Tìm đối tượng
            var updateModel = db.ChuongTrinhGGs.Find(modelCTGG.MaCT);
            //Gắn giá trị
            updateModel.TenSuKien = model.TenSuKien;
            updateModel.ThoiGianBD = model.ThoiGianBD;
            updateModel.ThoiGianKT = model.ThoiGianKT;
            updateModel.ThongTinSuKien = model.ThongTinSuKien;
            updateModel.PhanTram = model.PhanTram;
            if (fileAnh != null)
            {
                if (fileAnh.ContentLength > 0)
                {
                    string rootFolder = Server.MapPath("/assets/img/sales-slider/");
                    string pathEmail = rootFolder + fileAnh.FileName;
                    fileAnh.SaveAs(pathEmail);
                    //Luu thuoc tinh url hinhanh
                    model.Poster = "/assets/img/sales-slider/" + fileAnh.FileName;
                    updateModel.Poster = model.Poster;
                }
            }
            //Lưu thay đổi
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult XoaCTGG(string id)
        {
            THNNEntities1 db = new THNNEntities1();
            ChuongTrinhGG model2 = db.ChuongTrinhGGs.Find(id);
            db.ChuongTrinhGGs.Remove(model2);
            Session.Remove("Admin_Update-CTGG");
            db.SaveChanges();

            return RedirectToAction("Index");

        }

    }
}

THNN/Areas/Admin/Views/ChuongTrinhKhuyenMai/CapNhatCTGG.cshtml
@model THNN.Models.ChuongTrinhGG

@{
    ViewBag.Title = "Cập Nhật Chương Trình Giảm Giá";
    Layout = "~/Areas/Admin/Views/Shared/Layout_admin.cshtml";
}

<main>
    <section class="service_section">
        <div class="container">

            <h2>Cập Nhật</h2>

            @using (Html.BeginForm("CapNhatCTGG", "ChuongTrinhKhuyenMai", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Chương Trình Giảm Giá</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.MaCT, "Mã CT", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaCT, new { htmlAttributes = new { @class = "form-control", disabled = true } })
                    @Html.ValidationMessageFor(model => model.MaCT, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.TenSuKien, "Tên Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenSuKien, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenSuKien, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ThoiGianBD, "Thời Gian Bắt Đầu", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
                            DateTime? specificDate = Model.ThoiGianBD;
                            string formattedDate = specificDate?.ToString("yyyy-MM-dd");
                            <input class="form-control" name="ThoiGianBD" value="@formattedDate" type="date" />
                     }


                    
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ThoiGianKT, "Thời Gian Kết Thúc", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{

                        

                            DateTime? specificDate1 = Model.ThoiGianKT;
                            string formattedDate1 = specificDate1?.ToString("yyyy-MM-dd");
                            <input class="form-control" name="ThoiGianKT" value="@formattedDate1" type="date" />
                        


                    }
                </div>
            </div>

         

            <div class="form-group">
                @Html.LabelFor(model => model.PhanTram, "Phần Trăm", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhanTram, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhanTram, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ThongTinSuKien, "Thông Tin Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ThongTinSuKien, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ThongTinSuKien, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <label class="control-label col-md-2">Hình ảnh</label>
                <div class="col-md-10">
                    <img style="width:50px;height:40px" src="@Model.Poster" alt="">
                    <label for="labelFileAnh"> Thay đổi ảnh</label>
                    <input type="file" name="fileAnh" id="labelFileAnh" style="display: none;">
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        </div>
            }

            <div>
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </section>
</main>

THNN/Areas/Admin/Views/ChuongTrinhKhuyenMai/Index.cshtml
@model IEnumerable<THNN.Models.ChuongTrinhGG>


@{
    ViewBag.Title = "Chương Trình Giảm Giá";
    Layout = "~/Areas/Admin/Views/Shared/Layout_admin.cshtml";
}

<main>
    <section class="service_section">
        <div class="container-fluid">

            <h2>Danh Sách Sự Kiện</h2>

            <p>
                <a href="~/Admin/ChuongTrinhKhuyenMai/ThemMoiSuKien">Thêm mới</a>
            </p>
            <table class="table">
                <tr>
                    <th>
                        Mã CT
                    </th>
                    <th>
                        Tên Sự Kiện
                    </th>
                    <th>
                        Thông Tin Sự Kiện
                    </th>
                    <th>
                        Thời Gian BD
                    </th>
                    <th>
                        Thời Gian Kết Thúc
                    </th>
                    <th>
                       Poster
                    </th>
                    <th>
                        Phầm Trăm Giảm Giá
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    DateTime? date = item.ThoiGianBD;
                    DateTime? date2 = item.ThoiGianKT;
                    string ngayBD = date?.ToString("dd-MM-yyyy");
                    string ngayKT = date2?.ToString("dd-MM-yyyy");
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaCT)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenSuKien)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ThongTinSuKien)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => ngayBD)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => ngayKT)
                        </td>
                        <td>
                            <img src="@item.Poster" style="height:50px;width:200px" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhanTram)
                        </td>
                        <td>
                            @Html.ActionLink("Cập Nhật", "CapNhatCTGG", new { id = item.MaCT }) |
                            @Html.ActionLink("Xóa", "XoaCTGG", new { id = item.MaCT }) |
                            @Html.ActionLink("Thêm sản phẩm", "ThemSanPham", new { id = item.MaCT })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </section>
</main>

THNN/Areas/Admin/Views/ChuongTrinhKhuyenMai/ThemMoiKH.cshtml
@model THNN.Models.ChuongTrinhGG


@{
    ViewBag.Title = "Thêm mới chương trình ";
    Layout = "~/Areas/Admin/Views/Shared/Layout_admin.cshtml";
}

<main>
    <section class="service_section">
        <div class="container">

            <h2>Thêm Mới</h2>

            @using (Html.BeginForm("ThemMoiSuKien", "ChuongTrinhKhuyenMai", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Chương Trình Giảm Giá</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.TenSuKien, "Tên Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenSuKien, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenSuKien, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ThoiGianBD, "Thời Gian Bắt Đầu", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
                        DateTime specificDate = new DateTime(1991, 01, 01);
                        string formattedDate = specificDate.ToString("yyyy-MM-dd");
                        <input class="form-control" name="ThoiGianBD" value="@formattedDate" type="date" />
                    }
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ThoiGianKT, "Thời Gian Kết Thúc", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
                        DateTime specificDate2 = new DateTime(1991, 01, 01);
                        string formattedDate2 = specificDate2.ToString("yyyy-MM-dd");
                        <input class="form-control" name="ThoiGianKT" value="@formattedDate2" type="date" />
                    }
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.PhanTram, "Phần Trăm", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhanTram, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhanTram, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ThongTinSuKien, "Thông Tin Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ThongTinSuKien, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ThongTinSuKien, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Hình ảnh</label>
                <div class="col-md-10">
                    <input type="file" name="fileAnh" />
                    @Html.ValidationMessageFor(model => model.Poster, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
            }

            <div>
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </section>
</main>

THNN/Areas/Admin/Views/ChuongTrinhKhuyenMai/ThemMoiSuKien.cshtml
@model THNN.Models.ChuongTrinhGG


@{
    ViewBag.Title = "Thêm mới chương trình ";
    Layout = "~/Areas/Admin/Views/Shared/Layout_admin.cshtml";
}

<main>
    <section class="service_section">
        <div class="container">

            <h2>Thêm Mới</h2>

            @using (Html.BeginForm("ThemMoiSuKien", "ChuongTrinhKhuyenMai", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Chương Trình Giảm Giá</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.TenSuKien, "Tên Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenSuKien, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenSuKien, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ThoiGianBD, "Thời Gian Bắt Đầu", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @{
                                DateTime specificDate = new DateTime(1991, 01, 01);
                                string formattedDate = specificDate.ToString("yyyy-MM-dd");
                                <input class="form-control" name="ThoiGianBD" value="@formattedDate" type="date" />
                            }
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ThoiGianKT, "Thời Gian Kết Thúc", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @{
                                DateTime specificDate2 = new DateTime(1991, 01, 01);
                                string formattedDate2 = specificDate2.ToString("yyyy-MM-dd");
                                <input class="form-control" name="ThoiGianKT" value="@formattedDate2" type="date" />
                            }
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.PhanTram, "Phần Trăm", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhanTram, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhanTram, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ThongTinSuKien, "Thông Tin Sự Kiện", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ThongTinSuKien, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ThongTinSuKien, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2">Hình ảnh</label>
                        <div class="col-md-10">
                            <input type="file" name="fileAnh" />
                            @Html.ValidationMessageFor(model => model.Poster, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Thêm" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </section>
</main>

THNN/Areas/Admin/Views/ChuongTrinhKhuyenMai/ThemSanPham.cshtml
@model IEnumerable<THNN.Models.SanPham>

@{
    ViewBag.Title = "Danh sách sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/Layout_admin.cshtml";
}

<main>
    <section class="service_section">
        <div style=" padding-bottom: 40px;" class="container-fluid">
            @{
                string MaCT = Session["MACT_Update-CTGG"] as string;
            }

            <h2>Danh sách sản phẩm</h2>
            <table class="table">
                <tr>
                    @{
                        var checkAll = true;
                        foreach (var item in Model)
                        {
                            if (item.MaCT == null)
                            {
                                checkAll = false;
                            }
                        }
                    }

                    @if (checkAll == true)
                    {
                        <td id="click_all" class="details-control">
                            <input class="form-check-input" checked type="checkbox" id="checkboxNoLabel"
                                   value="" aria-label="...">
                        </td>
                    }
                    else
                    {
                        <td id="click_all" class="details-control">
                            <input class="form-check-input" type="checkbox" id="checkboxNoLabel"
                                   value="" aria-label="...">
                        </td>
                    }

                    <th>
                        Mã Sản Phẩm
                    </th>
                    <th>
                        Tên Sản Phẩm
                    </th>
                    <th>
                        Giá Bán
                    </th>
                    <th>
                        Trọng Lượng
                    </th>
                    <th>
                        Mô Tả
                    </th>
                    <th>
                        Số Lượng Tồn
                    </th>
                    <th>
                        Sản Xuất
                    </th>
                    <th>
                        Thương Hiệu
                    </th>
                    <th>
                        Hình Ảnh
                    </th>
                    <th>
                        Hình Ảnh Khác
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        @if (MaCT.Equals(item.MaCT))
                        {
                            <td class="details-control">
                                <input class="form-check-input" checked name="masp" type="checkbox"
                                       value="@item.MaSP" aria-label="...">
                            </td>
                        }
                        else
                        {
                            <td class="details-control">
                                <input class="form-check-input" name="masp" type="checkbox"
                                       value="@item.MaSP" aria-label="...">
                            </td>
                        }


                        <td>
                            @Html.DisplayFor(modelItem => item.MaSP)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenSP)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GiaBanSP)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TrongLuong)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MoTaSP)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoLuongT)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SanXuat)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ThuongHieu)
                        </td>
                        <td>
                            <img src="@item.HinhAnh" style="height:50px;width:50px" />
                        </td>
                        <td>
                            <img src="@item.HinhAnh1" style="height:50px;width:50px" />
                        </td>
                    </tr>
                }



            </table>

            @Html.ActionLink("Quay lại", "Index")

        </div>
    </section>
</main>

<script>
    var currentUrl = window.location.href;
    var parts = currentUrl.split('/');
    var value = parts[parts.length - 1];
    var listCheckBox = document.querySelectorAll("input[name = 'masp']")
    listCheckBox.forEach((item, index) => {
        item.addEventListener("change", function () {
            var itemSelectValue = item.value;

            var dataRequest = {
                itemChecked: item.checked,
                maSP: itemSelectValue,
                maCT: value
            }

            $.ajax({
                type: "POST",
                url: "/ChuongTrinhKhuyenMai/ThemSanPham",
                data: JSON.stringify(dataRequest),
                contentType: "application/json; charset=utf-8",
                success: function (response) {

                }
            })

        })
    })

    var clickAll = document.getElementById("click_all");
    clickAll.addEventListener("change", function () {
        var listSP = [];
        var itemChecked = false;
        if (clickAll.querySelector("input").checked) {
            listCheckBox.forEach(function (item) {
                item.checked = true;
                itemChecked = true;
                var maSP = item.value;
                listSP.push(maSP);
            })
        } else {
            listCheckBox.forEach(function (item) {
                item.checked = false;
                itemChecked = false;
                var maSP = item.value;
                listSP.push(maSP);
            })
        }

        var dataRequest = {
            ItemChecked: itemChecked,
            ListSP: listSP,
            MaCT: value
        }

        $.ajax({
            type: "POST",
            url: "/ChuongTrinhKhuyenMai/ThemSanPhamAll",
            data: JSON.stringify(dataRequest),
            contentType: "application/json; charset=utf-8",
            success: function (response) {

            }
        })

    })

</script>