THNN/Models/NhaCungCap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THNN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.PhieuNhaps = new HashSet<PhieuNhap>();
        }
    
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
    }
}

THNN/Areas/Admin/Controllers/NhaCungCapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using THNN.Models;

namespace THNN.Areas.Admin.Controllers
{
    public class NhaCungCapController : Controller
    {
        THNNEntities1 db = new THNNEntities1();

        // GET: Admin/NhaCungCap
        public ActionResult Index()
        {
            List<NhaCungCap> danhSachNCC = db.NhaCungCaps.ToList();
            return View(danhSachNCC);
        }

        public ActionResult ThemMoiNCC()
        {
            return View();
        }


        [HttpPost]
        public ActionResult ThemMoiNCC(NhaCungCap model)
        {
            List<NhaCungCap> danhSachNCC = db.NhaCungCaps.ToList();
            NhaCungCap nccLast = danhSachNCC.Last();
            string maNCC = "";
            string splitMaNCC = "";
            long newMaNCCInt = 0;
            string newMaNCCString = "";
            maNCC = nccLast.MaNCC;
            splitMaNCC = maNCC.Substring(3);
            if (Int64.TryParse(splitMaNCC, out newMaNCCInt))
            {
                newMaNCCInt++;
            }

            if (newMaNCCInt < 10)
            {
                newMaNCCString = "NCC0" + Convert.ToString(newMaNCCInt);
            }
            else if (newMaNCCInt > 10)
            {
                newMaNCCString = "NCC" + Convert.ToString(newMaNCCInt);
            }

            if (model.TenNCC == null || model.TenNCC.Equals(""))
            {
                ModelState.AddModelError("", "Vui lòng tên nhà cung cấp");
                return View(model);
            }

            if (model.DiaChi == null || model.DiaChi.Equals(""))
            {
                ModelState.AddModelError("", "Vui lòng điền địa chỉ");
                return View(model);
            }

            if (model.DienThoai == null || model.DienThoai.Equals(""))
            {
                ModelState.AddModelError("", "Vui lòng điền số điện thoại");
                return View(model);
            }
            model.MaNCC = newMaNCCString;
            db.NhaCungCaps.Add(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CapNhatNCC(string id)
        {
            //Tìm đối tượng
            NhaCungCap model = db.NhaCungCaps.Find(id);
            Session["Admin_Update-NCC"] = model;
            return View(model);
        }

        [HttpPost]
        public ActionResult CapNhatNCC(NhaCungCap model)
        {

            NhaCungCap modelNCC = Session["Admin_Update-NCC"] as NhaCungCap;
            //Tìm đối tượng
            var updateModel = db.NhaCungCaps.Find(modelNCC.MaNCC);
            //Gắn giá trị
            updateModel.MaNCC = modelNCC.MaNCC;
            updateModel.TenNCC = model.TenNCC;
            updateModel.DiaChi = model.DiaChi;
            updateModel.DienThoai = model.DienThoai;
            //Lưu thay đổi
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult XoaNCC(string id)
        {
            NhaCungCap model2 = db.NhaCungCaps.Find(id);
            db.NhaCungCaps.Remove(model2);
            db.SaveChanges();

            return RedirectToAction("Index");

        }

    }
}

THNN/Areas/Admin/Views/NhaCungCap/CapNhatNCC.cshtml
@model THNN.Models.NhaCungCap


@{
    ViewBag.Title = "Cập Nhật Nhà Cung Cấp";
    Layout = "~/Areas/Admin/Views/Shared/Layout_admin.cshtml";
}

<main>
    <section class="service_section">
        <div class="container">

            <h2>Cập Nhật</h2>

            @using (Html.BeginForm("CapNhatNCC", "NhaCungCap", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Nhà Cung Cấp</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.MaNCC, "Mã Nhà Cung Cấp", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MaNCC, new { htmlAttributes = new { @class = "form-control", disabled = true } })
                            @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TenNCC, "Tên Nhà Cung Cấp", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenNCC, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.DiaChi, "Địa Chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DienThoai, "Số Điện Thoại", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lưu" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </section>
</main>

THNN/Areas/Admin/Views/NhaCungCap/Index.cshtml
@model IEnumerable<THNN.Models.NhaCungCap>


@{
    ViewBag.Title = "Danh sách nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/Layout_admin.cshtml";
}

<main>
    <section class="service_section">
        <div class="container">

            <h2>Danh sách nhà cung cấp</h2>

            <p>
                <a href="~/Admin/NhaCungCap/ThemMoiNCC">Thêm mới</a>
            </p>
            <table class="table">
                <tr>
                    <th>
                        Mã Nhà Cung Cấp
                    </th>
                    <th>
                        Tên Nhà Cung Cấp
                    </th>
                    <th>
                        Địa Chỉ
                    </th>
                    <th>
                        Điện Thoại
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaNCC)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenNCC)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DiaChi)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DienThoai)
                        </td>
                        <td>
                            @Html.ActionLink("Cập nhật", "CapNhatNCC", new { id = item.MaNCC }) |
                            @Html.ActionLink("Xóa", "XoaNCC", new { id = item.MaNCC })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </section>
</main>

THNN/Areas/Admin/Views/NhaCungCap/ThemMoiNCC.cshtml
@model THNN.Models.NhaCungCap


@{
    ViewBag.Title = "Thêm mới nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/Layout_admin.cshtml";
}

<main>
    <section class="service_section">
        <div class="container">

            <h2>Thêm Mới</h2>

            @using (Html.BeginForm("ThemMoiNCC", "NhaCungCap", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Nhà Cung Cấp</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.TenNCC, "Tên Nhà Cung Cấp", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenNCC, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DiaChi, "Địa Chỉ Nhà Cung Cấp", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DienThoai, "Số Điện Thoại", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Tạo" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </section>
</main>